name: Test GO version
on:
  workflow_dispatch:
jobs:
  build:
    name: Test GO version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15' # The Go version to download (if necessary) and use.
      - name: Script to check go version
        run: ./test.sh
        env:
          GOROOT: "/opt/hostedtoolcache/go/1.15.2/x64"
