name: Test GO version
on:
  workflow_dispatch:
jobs:
  build:
    name: Test GO version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Script to check go version
        run: ./test.sh
        env:
          GOROOT: "/opt/hostedtoolcache/go/1.15.2/x64"
